In [24]:
from keras.datasets import mnist

In [25]:
#loading Data Set
(X_train, Y_train), (X_test,y_test)=  mnist.load_data()

In [26]:
# print Dataset shape
print("X_trian Shape", X_train)
print("X_train Shape", X_train.shape)

X_trian Shape [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
X_train Shape (60000, 28, 28)
X_trian Shape [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]


In [27]:
print("X_test shape", X_test.shape)
print("Y_train shape", Y_train.shape)
print("y_test Shape", y_test.shape)

X_test shape (10000, 28, 28)
Y_train shape (60000,)
y_test Shape (10000,)
X_test shape (10000, 28, 28)
Y_train shape (60000,)
y_test Shape (10000,)


In [28]:
from keras.models import Sequential
from keras.layers import Dense,Dropout,Conv2D,MaxPool2D, Flatten
from keras.utils import np_utils

In [29]:
#Flatting image from 28x28 pixels to 1D 787 pixels
X_train = X_train.reshape(60000,784)

In [30]:
X_test = X_test.reshape(10000,784)

In [31]:
Y_train= Y_train.astype('float32')

In [32]:
y_test = y_test.astype('float32')

In [33]:
#normalize the data to help with training
X_train = X_train/255
X_test = X_test/255

In [34]:
#One hot encoding using keras numpy related utilities
n_classes = 10
print("Shape before one hot encoding: ", Y_train.shape)

Shape before one hot encoding:  (60000,)
Shape before one hot encoding:  (60000,)


In [35]:
Y_train =np_utils.to_categorical(Y_train, n_classes)

In [36]:
y_test = np_utils.to_categorical(y_test,n_classes)

In [37]:
print(" Shape after one hot encoding:", Y_train.shape)

 Shape after one hot encoding: (60000, 10)
 Shape after one hot encoding: (60000, 10)


In [38]:
# Building a linear stack of layers with the sequential model
model = Sequential()

In [39]:
# Hidden layer
model.add(Dense(100,input_shape=(784,),activation='relu'))

In [40]:
# OutPut Layer
model.add(Dense(10,activation ='softmax'))

In [41]:
# looking at model summary
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 100)               78500     
_________________________________________________________________
dense_4 (Dense)              (None, 10)                1010      
Total params: 79,510
Trainable params: 79,510
Non-trainable params: 0
_________________________________________________________________
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 100)               78500     
_________________________________________________________________
dense_4 (Dense)              (None, 10)                1010      
Total params: 79,510
Trainable params: 79,510
Non-trainable params: 0
_________________________________________________________________


In [42]:
# compiling the sequential model
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

In [43]:
# training the model for 10 epochs
model.fit(X_train, Y_train, batch_size=128, epochs=10, validation_data=(X_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
  128/60000 [..............................] - ETA: 1:18 - loss: 2.2464 - accuracy: 0.1484Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 3s 52us/step - loss: 0.3758 - accuracy: 0.8984 - val_loss: 0.2064 - val_accuracy: 0.9416
Epoch 2/10
60000/60000 [==============================] - 3s 51us/step - loss: 0.1779 - accuracy: 0.9501 - val_loss: 0.1515 - val_accuracy: 0.9569
Epoch 3/10
60000/60000 [==============================] - 3s 49us/step - loss: 0.1309 - accuracy: 0.9629 - val_loss: 0.1202 - val_accuracy: 0.9638
Epoch 4/10
60000/60000 [==============================] - 3s 52us/step - loss: 0.1028 - accuracy: 0.9710 - val_loss: 0.1069 - val_accuracy: 0.9671
Epoch 5/10
60000/60000 [==============================] - 3s 51us/step - loss: 0.0852 - accuracy: 0.9756 - val_loss: 0.0955 - val_accuracy: 0.9706
Epoch 6/10
60000/60000 [==============================] - 3s 50u

In [47]:
# to calculate accuracy
from sklearn.metrics import accuracy_score

In [45]:
# compiling the sequential model
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')


## Building CNN Model

In [48]:
# keras imports for the dataset and building our neural network
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Conv2D, MaxPool2D, Flatten
from keras.utils import np_utils

# to calculate accuracy
from sklearn.metrics import accuracy_score

# loading the dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# building the input vector from the 28x28 pixels
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

# normalizing the data to help with the training
X_train /= 255
X_test /= 255

# one-hot encoding using keras' numpy-related utilities
n_classes = 10
print("Shape before one-hot encoding: ", y_train.shape)
Y_train = np_utils.to_categorical(y_train, n_classes)
Y_test = np_utils.to_categorical(y_test, n_classes)
print("Shape after one-hot encoding: ", Y_train.shape)

# building a linear stack of layers with the sequential model
model = Sequential()
# convolutional layer
model.add(Conv2D(25, kernel_size=(3,3), strides=(1,1), padding='valid', activation='relu', input_shape=(28,28,1)))
model.add(MaxPool2D(pool_size=(1,1)))
# flatten output of conv
model.add(Flatten())
# hidden layer
model.add(Dense(100, activation='relu'))
# output layer
model.add(Dense(10, activation='softmax'))

# compiling the sequential model
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

# training the model for 10 epochs
model.fit(X_train, Y_train, batch_size=128, epochs=10, validation_data=(X_test, Y_test))

Shape before one-hot encoding:  (60000,)
Shape after one-hot encoding:  (60000, 10)
Shape before one-hot encoding:  (60000,)
Shape after one-hot encoding:  (60000, 10)
Train on 60000 samples, validate on 10000 samples
Epoch 1/10
Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 60s 992us/step - loss: 0.2018 - accuracy: 0.9408 - val_loss: 0.0840 - val_accuracy: 0.9752
Epoch 2/10
60000/60000 [==============================] - 58s 973us/step - loss: 0.0646 - accuracy: 0.9808 - val_loss: 0.0617 - val_accuracy: 0.9790
Epoch 3/10
60000/60000 [==============================] - 58s 962us/step - loss: 0.0374 - accuracy: 0.9887 - val_loss: 0.0563 - val_accuracy: 0.9826
Epoch 4/10
60000/60000 [==============================] - 60s 1ms/step - loss: 0.0226 - accuracy: 0.9935 - val_loss: 0.0575 - val_accuracy: 0.9814
Epoch 5/10
60000/60000 [==============================] - 58s 965us/step - loss: 0.0155 - accuracy: 0.9954 - val_loss: 0.0602 -